### PR TITLE
Include licensing

### PR DESCRIPTION
**Pull request by mjmenger**
this adds support for bigip_license != "" 
if the license is not an empty string a byol image is selected
if the license is not an empty string bigip_license is set in the inventory.yml file

### CODE REVIEW

**Review by aknot242 — APPROVED** [review]
I haven't run it, but the logic seems sound to me!

**Comment by mjmenger** [comment]
> I haven't run it, but the logic seems sound to me!

my primary concern is that the management of paygo/byol is a hack and doesn't look anything like the real world. Perhaps I'm overthinking it.

**Review by codygreen — APPROVED** [review]
looks good

**Comment by codygreen** [comment]
I understand your concern but I don't think there is a better way to handle this

**Pull request merged**
